#cloud-config

packages:
  - curl
  - ufw

runcmd:
  - curl -fsSL https://get.docker.com | sh
  - adduser --disabled-password --gecos "" cloudmart
  - usermod -aG sudo,docker cloudmart
  - mkdir -p /home/cloudmart/.ssh
  - cp /root/.ssh/authorized_keys /home/cloudmart/.ssh/
  - chown -R cloudmart:cloudmart /home/cloudmart/.ssh
  - chmod 700 /home/cloudmart/.ssh
  - chmod 600 /home/cloudmart/.ssh/authorized_keys
  - ufw --force enable
  - ufw allow 22/tcp
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw default deny incoming
  - ufw default allow outgoing
  - systemctl enable docker
  - systemctl start docker
  - docker network create proxy
